---
- hosts: all
  vars:
    esxiiso: 'VMware-VMvisor-Installer-8.0U2-22380479.x86_64.iso'
    vcenteriso: 'VMware-VCSA-all-8.0.2-22617221.iso'
    mountdev: '/dev/xvdc'
    mountpath: '/data'
    installtools: false
# tag copyiso to push isos

  tasks:

    - debug:
        msg: 
         #- "{{ ansible_facts }}"
         #- "{{ ansible_facts.mounts | selectattr('mount', '==', '/data') }}"
         - "{{ ansible_facts.mounts }}"

    - name: set fact for mount point
      set_fact:
        mountpoint: "{{ ansible_facts.mounts | selectattr('mount', '==', '/data') }}"

    - debug:
        msg: 
          - "{{ mountpoint[0].mount }}"

    - name: set up mount point for isos
      block:
        - name: "Create {{ mountdev }} partition"
          parted:
            device: "{{ mountdev }}"
            number: 1
            state: present
            fs_type: ext4
      
        - name: "Format {{ mountdev }} partition"
          filesystem:
            dev: "{{ mountdev }}"
            fstype: ext4
      
        - name: "Mount {{ mountdev }} partition at {{ mountpath }}"
          mount:
            src: "{{ mountdev }}"
            path: "{{ mountpath }}"
            fstype: ext4
            state: mounted
      when: mountpoint[0].mount != "/data" 
      #when: ansible_facts.mounts | selectattr('mount', '==', '/data') | length == 0
  
    - name: Install NFS server
      package:
        name: nfs-utils
        state: present
 
    - name: Install bind utils dig
      package:
        name: bind-utils
        state: present
 
    - name: Create export file
      file:
        path: /etc/exports
        state: touch
        owner: root
        group: root
        mode: 0644
  
    - name: "Add export to file {{ mountpath }}/export/share"
      lineinfile:
        path: /etc/exports
        line: "{{ mountpath }}/export/share *(sync)"
        state: present
        owner: root
        group: root
        mode: 0644
 
    - name: "Add export to file {{ mountpath }}/export/backups"
      lineinfile:
        path: /etc/exports
        line: "{{ mountpath }}/export/backups *(sync,rw,all_squash)"
        state: present
        owner: root
        group: root
        mode: 0644
 
    - name: Start NFS service
      service:
        name: nfs-server
        state: started
        enabled: yes
  
    - name: Create directory
      file:
        path: "{{ mountpath }}/export/share"
        state: directory
        mode: 0755
 
    - name: Create directory
      file:
        path: "{{ mountpath }}/export/backups"
        state: directory
        mode: 0777
 
    - name: Copy ISO file esxi
      copy:
        src: "~/Downloads/{{ item }}"
        dest: "{{ mountpath }}/export/share/{{ item }}"
        mode: 0644
      loop:
        - "{{ esxiiso }}"
      tags:
        - copyiso
        - never
  
    - name: Copy ISO file vcenter
      copy:
        src: "~/Downloads/{{ item }}"
        dest: "{{ mountpath }}/export/share/{{ item }}"
        mode: 0644
      loop:
        - "{{ vcenteriso }}"
      tags:
        - copyiso
        - never

    - name: Install, configure, and start Apache
      block:
        - name: Install govc cli (Need gateway set up)
          shell: 'curl -L -o - "https://github.com/vmware/govmomi/releases/latest/download/govc_$(uname -s)_$(uname -m).tar.gz" | tar -C /usr/local/bin -xvzf - govc'
                                                        
        - name: Install ibmcloud cli (Need gateway set up)
          shell: 'curl -fsSL https://clis.cloud.ibm.com/install/linux | sh'
    
        - name: Install ibmcloud plugins (Need gateway set up)
          shell: '{{ item }}'
          loop:
            - ibmcloud cf install -f
            - ibmcloud plugin install vpc-infrastructure -f
            - ibmcloud plugin install cloud-dns-services -f
            - ibmcloud plugin install cloud-object-storage -f
            - ibmcloud plugin install schematics -f
      when: installtools | bool
