---
- hosts: all
  vars:
    esxiiso: 'VMware-VMvisor-Installer-8.0U1-21495797.x86_64.iso'
#    esxiiso: 'VMware-VMvisor-Installer-7.0U3l-21424296.x86_64.iso'
    vcenteriso: 'VMware-VCSA-all-8.0.1-21560480.iso'
#    vcenteriso: 'VMware-VCSA-all-7.0.3-21477706.iso'
    mountdev: '/dev/xvdc'
    mountpath: '/data'
    copyiso: false

  tasks:

    - name: set up mount point for isos
      block:
        - name: "Create {{ mountdev }} partition"
          parted:
            device: "{{ mountdev }}"
            number: 1
            state: present
            fs_type: ext4
      
        - name: "Format {{ mountdev }} partition"
          filesystem:
            dev: "{{ mountdev }}"
            fstype: ext4
      
        - name: "Mount {{ mountdev }} partition at {{ mountpath }}"
          mount:
            src: "{{ mountdev }}"
            path: "{{ mountpath }}"
            fstype: ext4
            state: mounted
      when: ansible_facts.mounts | selectattr('mount', '==', '/data') | length == 0
  
    - name: Install NFS server
      package:
        name: nfs-utils
        state: present
 
    - name: Install bind utils dig
      package:
        name: bind-utils
        state: present
 
    - name: Create export file
      file:
        path: /etc/exports
        state: touch
        owner: root
        group: root
        mode: 0644
  
    - name: "Add export to file {{ mountpath }}/export/share"
      lineinfile:
        path: /etc/exports
        line: "{{ mountpath }}/export/share *(sync)"
        state: present
        owner: root
        group: root
        mode: 0644
 
    - name: "Add export to file {{ mountpath }}/export/backups"
      lineinfile:
        path: /etc/exports
        line: "{{ mountpath }}/export/backups *(sync,rw,all_squash)"
        state: present
        owner: root
        group: root
        mode: 0644
 
    - name: Start NFS service
      service:
        name: nfs-server
        state: started
        enabled: yes
  
    - name: Create directory
      file:
        path: "{{ mountpath }}/export/share"
        state: directory
        mode: 0755
 
    - name: Create directory
      file:
        path: "{{ mountpath }}/export/backups"
        state: directory
        mode: 0777
 
    - name: Copy ISO file esxi
      copy:
        src: "~/Downloads/{{ esxiiso }}"
        dest: "{{ mountpath }}/export/share/{{ esxiiso}}"
        mode: 0644
      when: copyiso | bool
  
    - name: Copy ISO file vcenter
      copy:
        src: "~/Downloads/{{ vcenteriso }}"
        dest: "{{ mountpath }}/export/share/{{ vcenteriso }}"
        mode: 0644
      when: copyiso | bool

    - name: Install govc cli
      shell: 'curl -L -o - "https://github.com/vmware/govmomi/releases/latest/download/govc_$(uname -s)_$(uname -m).tar.gz" | tar -C /usr/local/bin -xvzf - govc'
                                                    
    - name: Install ibmcloud cli
      shell: 'curl -fsSL https://clis.cloud.ibm.com/install/linux | sh'


    - name: Install ibmcloud plugins
      shell: '{{ item }}'
      loop:
        - ibmcloud cf install -f
        - ibmcloud plugin install vpc-infrastructure -f
        - ibmcloud plugin install cloud-dns-services -f
        - ibmcloud plugin install cloud-object-storage -f
        - ibmcloud plugin install schematics -f
